"""Add workflow_id to Report model and relationship to Workflow

Revision ID: dc69dea9ba0a
Revises: 87b1a54130b7
Create Date: 2025-06-29 22:30:33.095943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc69dea9ba0a'
down_revision: Union[str, Sequence[str], None] = '87b1a54130b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add workflow_id column to reports table
    op.add_column('reports', sa.Column('workflow_id', sa.UUID(), nullable=False))
    
    # Create index for workflow_id
    op.create_index('idx_reports_workflow', 'reports', ['workflow_id'], unique=False, schema='public')
    
    # Add foreign key constraint
    op.create_foreign_key(None, 'reports', 'workflows', ['workflow_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraint
    op.drop_constraint(None, 'reports', type_='foreignkey')
    
    # Drop index
    op.drop_index('idx_reports_workflow', table_name='reports', schema='public')
    
    # Drop workflow_id column
    op.drop_column('reports', 'workflow_id')
    # ### end Alembic commands ###
